// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCodeFirstODataMySQL.Database_Context;

#nullable disable

namespace WebCodeFirstODataMySQL.Migrations
{
    [DbContext(typeof(EmpDetailsContext))]
    [Migration("20241015103343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebCodeFirstODataMySQL.Models.Department", b =>
                {
                    b.Property<Guid?>("DeptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("LocationID")
                        .HasColumnType("char(36)");

                    b.HasKey("DeptID");

                    b.HasIndex("LocationID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("WebCodeFirstODataMySQL.Models.Employee", b =>
                {
                    b.Property<Guid?>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long?>("ContactNo")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DOJ")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeptID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("longblob");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpId");

                    b.HasIndex("DeptID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WebCodeFirstODataMySQL.Models.Location", b =>
                {
                    b.Property<Guid?>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("LocationName")
                        .HasColumnType("longtext");

                    b.HasKey("LocationID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("WebCodeFirstODataMySQL.Models.Department", b =>
                {
                    b.HasOne("WebCodeFirstODataMySQL.Models.Location", "Location")
                        .WithMany("Departments")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WebCodeFirstODataMySQL.Models.Employee", b =>
                {
                    b.HasOne("WebCodeFirstODataMySQL.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebCodeFirstODataMySQL.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WebCodeFirstODataMySQL.Models.Location", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
